id: hds-hackathon.electronichealth.se
canonical: https://electronichealth.se/hds-hackathon
name: Hackathon Example IG
title: Hackathon Example IG
description: An Implementation Guide with examples for the Health Data Sweden Hackathon
status: draft # draft | active | retired | unknown
experimental: true
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
#fhirVersion: 4.3.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC-BY-SA-3.0-IGO # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#SE
publisher:
  name: HDS
  url: http://hds-hackathon.se
  # email: test@example.org

dependencies:
#  hl7.fhir.core:
#    id: r4b
#    version: 4.6.0
#    reason: |
#      This IG leverages subscription constructs pre-adopted from R4B.  Importing this IG makes the relevant terminologies available.
  # NOTE: These dependencies are required because SUSHI doesn't load transitive dependencies
  # See the zulip thread here: https://chat.fhir.org/#narrow/stream/215610-shorthand/search/transitive
  hl7.terminology: 5.5.0
  hl7.fhir.uv.extensions.r4: 5.1.0
  # Actual dependencies
  hl7se.fhir.base: 1.0.0


pages:
  index.md:
    title: Home

menu:
  Home: 
    Summary: index.html
    Changes: changes.html
    Dependencies: dependencies.html
    References: references.html
    Adapting Guidelines for Country use: adapting.html
  Business Requirements: 
    Concepts: concepts.html
    Generic Personas: personas.html
    User Scenarios: scenarios.html
    Business Processes: business-processes.html
    Data Dictionary: dictionary.html
    Decision-support Logic: decision-logic.html
    Indicator and Performance Metrics: indicators.html
    Functional Requirements: functional-requirements.html
    Non-functional Requirements: non-functional-requirements.html
  Data Models and Exchange:
    System Actors: system-actors.html
    Sequence Diagrams: sequence-diagrams.html
    Transactions: transactions.html
    Indicators and Measures: indicators-measures.html
    Codings: codings.html

  Deployment:
    Security and Privacy Considerations: security-privacy.html
    Testing: testing.html
    Test Data: test-data.html
    Reference Implementations: reference-implementations.html
    Trust Domains: trust_domain.html
    Downloads: downloads.html

  Indices:
    Artifact Index: artifacts.html
    Mappings: maps.html
    
