id: hl7.fhir.eu.ig-empty
canonical: https://hl7.eu/fhir/ig-empty
name: IGEmpty
title: Empty IG
description: An empty Implementation Guide to be used as a starting point for building HL7 EU Implementation Guides
status: draft # draft | active | retired | unknown
experimental: false
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
#fhirVersion: 4.3.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC-BY-SA-3.0-IGO # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 EU
  url: http://hl7.eu
  # email: test@example.org

dependencies:
#  hl7.fhir.core:
#    id: r4b
#    version: 4.6.0
#    reason: |
#      This IG leverages subscription constructs pre-adopted from R4B.  Importing this IG makes the relevant terminologies available.
  # NOTE: These dependencies are required because SUSHI doesn't load transitive dependencies
  # See the zulip thread here: https://chat.fhir.org/#narrow/stream/215610-shorthand/search/transitive
  hl7.terminology: 5.5.0
  hl7.fhir.uv.extensions.r4: 5.1.0
  hl7.fhir.uv.cql: 1.0.0
  hl7.fhir.uv.crmi: 1.0.0
  hl7.fhir.uv.sdc: 3.0.0
  hl7.fhir.uv.cpg: 2.0.0
  hl7.fhir.us.cqfmeasures: 5.0.0
  # Actual dependencies
  smart.who.int.base:
    id: sb
    version: 0.1.0
    reason: This IG uses SMART base computable guideline capabilities
  smart.who.int.base-clinical:
    id: sbc
    version: dev
    reason: This IG uses SMART base clinical capabilities

meta:
  profile:
    - http://smart.who.int/base/StructureDefinition/SGImplementationGuide

pages:
  index.md:
    title: Home

menu:
  Home: 
    Summary: index.html
    Changes: changes.html
    Dependencies: dependencies.html
    References: references.html
    Adapting Guidelines for Country use: adapting.html
  Business Requirements: 
    Concepts: concepts.html
    Generic Personas: personas.html
    User Scenarios: scenarios.html
    Business Processes: business-processes.html
    Data Dictionary: dictionary.html
    Decision-support Logic: decision-logic.html
    Indicator and Performance Metrics: indicators.html
    Functional Requirements: functional-requirements.html
    Non-functional Requirements: non-functional-requirements.html
  Data Models and Exchange:
    System Actors: system-actors.html
    Sequence Diagrams: sequence-diagrams.html
    Transactions: transactions.html
    Indicators and Measures: indicators-measures.html
    Codings: codings.html

  Deployment:
    Security and Privacy Considerations: security-privacy.html
    Testing: testing.html
    Test Data: test-data.html
    Reference Implementations: reference-implementations.html
    Trust Domains: trust_domain.html
    Downloads: downloads.html

  Indices:
    Artifact Index: artifacts.html
    Mappings: maps.html
    
